// 50 professional high-frequency AI usage domains
export const CATEGORIES = [
  { name: "Web Development", slug: "web-development", icon: "Globe", color: "#3B82F6", description: "AI skills for building modern websites, web applications, and frontend/backend development" },
  { name: "App Development", slug: "app-development", icon: "Smartphone", color: "#8B5CF6", description: "Mobile and desktop application development with AI assistance" },
  { name: "Office Productivity", slug: "office-productivity", icon: "Briefcase", color: "#F59E0B", description: "AI-powered office automation, document processing, and productivity tools" },
  { name: "Video Production", slug: "video-production", icon: "Video", color: "#EF4444", description: "AI skills for video editing, generation, post-production, and visual effects" },
  { name: "Image Creation", slug: "image-creation", icon: "Image", color: "#EC4899", description: "AI image generation, editing, enhancement, and graphic design" },
  { name: "Academic Writing", slug: "academic-writing", icon: "GraduationCap", color: "#6366F1", description: "Research paper writing, literature review, citation management, and academic formatting" },
  { name: "Official Document Writing", slug: "official-document-writing", icon: "FileText", color: "#14B8A6", description: "Government documents, official reports, policy drafting, and formal correspondence" },
  { name: "Legal Domain", slug: "legal-domain", icon: "Scale", color: "#78716C", description: "Legal document drafting, contract analysis, case research, and compliance checking" },
  { name: "Animation Production", slug: "animation-production", icon: "Film", color: "#F97316", description: "2D/3D animation creation, motion graphics, and character animation" },
  { name: "Entrepreneurship", slug: "entrepreneurship", icon: "Rocket", color: "#10B981", description: "Business planning, pitch deck creation, market analysis, and startup tools" },
  { name: "Data Science", slug: "data-science", icon: "BarChart3", color: "#0EA5E9", description: "Data analysis, visualization, machine learning, and statistical modeling" },
  { name: "DevOps & Cloud", slug: "devops-cloud", icon: "Cloud", color: "#6366F1", description: "CI/CD pipelines, cloud infrastructure, container orchestration, and monitoring" },
  { name: "Cybersecurity", slug: "cybersecurity", icon: "Shield", color: "#DC2626", description: "Security auditing, vulnerability assessment, penetration testing, and threat analysis" },
  { name: "UI/UX Design", slug: "ui-ux-design", icon: "Palette", color: "#D946EF", description: "User interface design, user experience research, prototyping, and design systems" },
  { name: "Marketing & SEO", slug: "marketing-seo", icon: "TrendingUp", color: "#F59E0B", description: "Digital marketing, SEO optimization, content strategy, and campaign management" },
  { name: "E-commerce", slug: "e-commerce", icon: "ShoppingCart", color: "#22C55E", description: "Online store management, product listing optimization, and sales automation" },
  { name: "Finance & Accounting", slug: "finance-accounting", icon: "DollarSign", color: "#059669", description: "Financial analysis, bookkeeping automation, tax preparation, and investment research" },
  { name: "Healthcare", slug: "healthcare", icon: "Heart", color: "#EF4444", description: "Medical documentation, clinical decision support, patient communication, and health data analysis" },
  { name: "Education & Training", slug: "education-training", icon: "BookOpen", color: "#8B5CF6", description: "Course creation, lesson planning, student assessment, and educational content generation" },
  { name: "Customer Service", slug: "customer-service", icon: "Headphones", color: "#0EA5E9", description: "Chatbot development, ticket routing, response templates, and customer satisfaction analysis" },
  { name: "Content Creation", slug: "content-creation", icon: "PenTool", color: "#EC4899", description: "Blog writing, social media content, copywriting, and content repurposing" },
  { name: "Translation & Localization", slug: "translation-localization", icon: "Languages", color: "#6366F1", description: "Multi-language translation, localization workflows, and cultural adaptation" },
  { name: "Audio & Music", slug: "audio-music", icon: "Music", color: "#A855F7", description: "Music generation, audio editing, podcast production, and sound design" },
  { name: "Game Development", slug: "game-development", icon: "Gamepad2", color: "#F97316", description: "Game design, NPC dialogue, level generation, and game testing automation" },
  { name: "3D Modeling", slug: "3d-modeling", icon: "Box", color: "#14B8A6", description: "3D model creation, texturing, rendering, and scene composition" },
  { name: "Database Management", slug: "database-management", icon: "Database", color: "#3B82F6", description: "Database design, query optimization, migration scripts, and data modeling" },
  { name: "API Development", slug: "api-development", icon: "Plug", color: "#10B981", description: "RESTful API design, GraphQL schemas, API documentation, and integration testing" },
  { name: "Machine Learning", slug: "machine-learning", icon: "Brain", color: "#7C3AED", description: "ML model training, hyperparameter tuning, feature engineering, and model deployment" },
  { name: "Natural Language Processing", slug: "nlp", icon: "MessageSquare", color: "#0891B2", description: "Text classification, sentiment analysis, named entity recognition, and language understanding" },
  { name: "Computer Vision", slug: "computer-vision", icon: "Eye", color: "#DC2626", description: "Image recognition, object detection, OCR, and visual inspection automation" },
  { name: "Blockchain & Web3", slug: "blockchain-web3", icon: "Link", color: "#F59E0B", description: "Smart contract development, DeFi protocols, NFT creation, and blockchain analysis" },
  { name: "IoT & Embedded", slug: "iot-embedded", icon: "Cpu", color: "#6366F1", description: "IoT device programming, sensor data processing, and embedded system automation" },
  { name: "Project Management", slug: "project-management", icon: "KanbanSquare", color: "#22C55E", description: "Task planning, sprint management, resource allocation, and progress tracking" },
  { name: "Human Resources", slug: "human-resources", icon: "Users", color: "#EC4899", description: "Resume screening, job description writing, interview preparation, and HR analytics" },
  { name: "Real Estate", slug: "real-estate", icon: "Building2", color: "#78716C", description: "Property analysis, listing descriptions, market reports, and investment evaluation" },
  { name: "Supply Chain", slug: "supply-chain", icon: "Truck", color: "#0EA5E9", description: "Inventory management, logistics optimization, demand forecasting, and supplier evaluation" },
  { name: "Social Media", slug: "social-media", icon: "Share2", color: "#F97316", description: "Social media management, content scheduling, engagement analysis, and influencer research" },
  { name: "Email Marketing", slug: "email-marketing", icon: "Mail", color: "#EF4444", description: "Email campaign creation, A/B testing, subscriber segmentation, and deliverability optimization" },
  { name: "Presentation Design", slug: "presentation-design", icon: "Presentation", color: "#A855F7", description: "Slide deck creation, visual storytelling, data visualization, and presentation coaching" },
  { name: "Technical Documentation", slug: "technical-documentation", icon: "FileCode", color: "#14B8A6", description: "API docs, user manuals, system architecture docs, and knowledge base articles" },
  { name: "Quality Assurance", slug: "quality-assurance", icon: "CheckCircle", color: "#22C55E", description: "Test case generation, bug report writing, regression testing, and QA automation" },
  { name: "Architecture Design", slug: "architecture-design", icon: "Building", color: "#78716C", description: "Architectural visualization, floor plan generation, material selection, and design review" },
  { name: "Environmental Science", slug: "environmental-science", icon: "Leaf", color: "#10B981", description: "Environmental impact assessment, sustainability reporting, and climate data analysis" },
  { name: "Journalism", slug: "journalism", icon: "Newspaper", color: "#3B82F6", description: "News writing, fact-checking, investigative research, and editorial content" },
  { name: "Photography", slug: "photography", icon: "Camera", color: "#D946EF", description: "Photo editing, color grading, composition analysis, and photography workflow automation" },
  { name: "Robotics", slug: "robotics", icon: "Bot", color: "#6366F1", description: "Robot programming, path planning, sensor fusion, and robotic process automation" },
  { name: "Aerospace", slug: "aerospace", icon: "Plane", color: "#0891B2", description: "Flight simulation, satellite data analysis, aerospace engineering calculations" },
  { name: "Biotech & Pharma", slug: "biotech-pharma", icon: "Microscope", color: "#DC2626", description: "Drug discovery, molecular modeling, clinical trial analysis, and bioinformatics" },
  { name: "Automotive", slug: "automotive", icon: "Car", color: "#F59E0B", description: "Vehicle diagnostics, autonomous driving algorithms, and automotive design" },
  { name: "Telecommunications", slug: "telecommunications", icon: "Radio", color: "#7C3AED", description: "Network optimization, signal processing, 5G planning, and telecom analytics" },
];
